//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowfounding.Resources.Pages.CompanyPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateCompany {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateCompany() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowfounding.Resources.Pages.CompanyPages.CreateCompany", typeof(CreateCompany).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string Bonuse_Definition {
            get {
                return ResourceManager.GetString("Bonuse_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Bonuse_Description {
            get {
                return ResourceManager.GetString("Bonuse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Bonuse_Title {
            get {
                return ResourceManager.GetString("Bonuse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonuses.
        /// </summary>
        internal static string Bonuses_Title {
            get {
                return ResourceManager.GetString("Bonuses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Images.
        /// </summary>
        internal static string Choose_Images {
            get {
                return ResourceManager.GetString("Choose_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Main Image.
        /// </summary>
        internal static string Choose_MainImage {
            get {
                return ResourceManager.GetString("Choose_MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create bonuse.
        /// </summary>
        internal static string CreateBonuse {
            get {
                return ResourceManager.GetString("CreateBonuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date end.
        /// </summary>
        internal static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Money.
        /// </summary>
        internal static string NeedMoney {
            get {
                return ResourceManager.GetString("NeedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Company.
        /// </summary>
        internal static string Title_Create {
            get {
                return ResourceManager.GetString("Title_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create company.
        /// </summary>
        internal static string Title_CreateCompany {
            get {
                return ResourceManager.GetString("Title_CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit company.
        /// </summary>
        internal static string Title_EditCompany {
            get {
                return ResourceManager.GetString("Title_EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image loading.
        /// </summary>
        internal static string Toaster_LoadImage_Title {
            get {
                return ResourceManager.GetString("Toaster_LoadImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images loading completed.
        /// </summary>
        internal static string Toaster_LoadImages_Message {
            get {
                return ResourceManager.GetString("Toaster_LoadImages_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Image loading completed.
        /// </summary>
        internal static string Toaster_LoadMainImage_Message {
            get {
                return ResourceManager.GetString("Toaster_LoadMainImage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Video.
        /// </summary>
        internal static string URLVideo {
            get {
                return ResourceManager.GetString("URLVideo", resourceCulture);
            }
        }
    }
}
