//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowfounding.Resources.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserBonusesReceived {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserBonusesReceived() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowfounding.Resources.Components.UserBonusesReceived", typeof(UserBonusesReceived).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Modal_Details {
            get {
                return ResourceManager.GetString("Modal_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated.
        /// </summary>
        internal static string Modal_Donated {
            get {
                return ResourceManager.GetString("Modal_Donated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Money.
        /// </summary>
        internal static string Modal_NeedMoney {
            get {
                return ResourceManager.GetString("Modal_NeedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus name.
        /// </summary>
        internal static string Table_Bonus_Title {
            get {
                return ResourceManager.GetString("Table_Bonus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string Table_Company_Name {
            get {
                return ResourceManager.GetString("Table_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Money.
        /// </summary>
        internal static string Table_Company_NeedMoney {
            get {
                return ResourceManager.GetString("Table_Company_NeedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAt.
        /// </summary>
        internal static string Table_CreateAt {
            get {
                return ResourceManager.GetString("Table_CreateAt", resourceCulture);
            }
        }
    }
}
